// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "k8s.io/api/core/v1"
	math "math"
	v1alpha1 "ssd-git.juniper.net/contrail/cn2/contrail/pkg/apis/core/v1alpha1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response_Action int32

const (
	Response_ADD    Response_Action = 0
	Response_UPDATE Response_Action = 1
	Response_DELETE Response_Action = 2
)

var Response_Action_name = map[int32]string{
	0: "ADD",
	1: "UPDATE",
	2: "DELETE",
}

var Response_Action_value = map[string]int32{
	"ADD":    0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x Response_Action) String() string {
	return proto.EnumName(Response_Action_name, int32(x))
}

func (Response_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1, 0}
}

type SubscriptionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionRequest) Reset()         { *m = SubscriptionRequest{} }
func (m *SubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*SubscriptionRequest) ProtoMessage()    {}
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *SubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionRequest.Unmarshal(m, b)
}
func (m *SubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *SubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionRequest.Merge(m, src)
}
func (m *SubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_SubscriptionRequest.Size(m)
}
func (m *SubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionRequest proto.InternalMessageInfo

func (m *SubscriptionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	New                  *Resource       `protobuf:"bytes,1,opt,name=new,proto3" json:"new,omitempty"`
	Old                  *Resource       `protobuf:"bytes,2,opt,name=old,proto3" json:"old,omitempty"`
	Action               Response_Action `protobuf:"varint,3,opt,name=action,proto3,enum=github.com.michaelhenkel.config_controller.pkg.apis.v1.Response_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetNew() *Resource {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *Response) GetOld() *Resource {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *Response) GetAction() Response_Action {
	if m != nil {
		return m.Action
	}
	return Response_ADD
}

type Resource struct {
	// Types that are valid to be assigned to Resource:
	//	*Resource_VirtualNetwork
	//	*Resource_VirtualMachineInterface
	//	*Resource_VirtualRouter
	//	*Resource_VirtualMachine
	//	*Resource_InstanceIP
	//	*Resource_RoutingInstance
	//	*Resource_Namespace
	Resource             isResource_Resource `protobuf_oneof:"resource"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{2}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

type isResource_Resource interface {
	isResource_Resource()
}

type Resource_VirtualNetwork struct {
	VirtualNetwork *v1alpha1.VirtualNetwork `protobuf:"bytes,1,opt,name=virtualNetwork,proto3,oneof"`
}

type Resource_VirtualMachineInterface struct {
	VirtualMachineInterface *v1alpha1.VirtualMachineInterface `protobuf:"bytes,2,opt,name=virtualMachineInterface,proto3,oneof"`
}

type Resource_VirtualRouter struct {
	VirtualRouter *v1alpha1.VirtualRouter `protobuf:"bytes,3,opt,name=virtualRouter,proto3,oneof"`
}

type Resource_VirtualMachine struct {
	VirtualMachine *v1alpha1.VirtualMachine `protobuf:"bytes,4,opt,name=virtualMachine,proto3,oneof"`
}

type Resource_InstanceIP struct {
	InstanceIP *v1alpha1.InstanceIP `protobuf:"bytes,5,opt,name=instanceIP,proto3,oneof"`
}

type Resource_RoutingInstance struct {
	RoutingInstance *v1alpha1.RoutingInstance `protobuf:"bytes,6,opt,name=routingInstance,proto3,oneof"`
}

type Resource_Namespace struct {
	Namespace *v1.Namespace `protobuf:"bytes,7,opt,name=namespace,proto3,oneof"`
}

func (*Resource_VirtualNetwork) isResource_Resource() {}

func (*Resource_VirtualMachineInterface) isResource_Resource() {}

func (*Resource_VirtualRouter) isResource_Resource() {}

func (*Resource_VirtualMachine) isResource_Resource() {}

func (*Resource_InstanceIP) isResource_Resource() {}

func (*Resource_RoutingInstance) isResource_Resource() {}

func (*Resource_Namespace) isResource_Resource() {}

func (m *Resource) GetResource() isResource_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *Resource) GetVirtualNetwork() *v1alpha1.VirtualNetwork {
	if x, ok := m.GetResource().(*Resource_VirtualNetwork); ok {
		return x.VirtualNetwork
	}
	return nil
}

func (m *Resource) GetVirtualMachineInterface() *v1alpha1.VirtualMachineInterface {
	if x, ok := m.GetResource().(*Resource_VirtualMachineInterface); ok {
		return x.VirtualMachineInterface
	}
	return nil
}

func (m *Resource) GetVirtualRouter() *v1alpha1.VirtualRouter {
	if x, ok := m.GetResource().(*Resource_VirtualRouter); ok {
		return x.VirtualRouter
	}
	return nil
}

func (m *Resource) GetVirtualMachine() *v1alpha1.VirtualMachine {
	if x, ok := m.GetResource().(*Resource_VirtualMachine); ok {
		return x.VirtualMachine
	}
	return nil
}

func (m *Resource) GetInstanceIP() *v1alpha1.InstanceIP {
	if x, ok := m.GetResource().(*Resource_InstanceIP); ok {
		return x.InstanceIP
	}
	return nil
}

func (m *Resource) GetRoutingInstance() *v1alpha1.RoutingInstance {
	if x, ok := m.GetResource().(*Resource_RoutingInstance); ok {
		return x.RoutingInstance
	}
	return nil
}

func (m *Resource) GetNamespace() *v1.Namespace {
	if x, ok := m.GetResource().(*Resource_Namespace); ok {
		return x.Namespace
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Resource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Resource_VirtualNetwork)(nil),
		(*Resource_VirtualMachineInterface)(nil),
		(*Resource_VirtualRouter)(nil),
		(*Resource_VirtualMachine)(nil),
		(*Resource_InstanceIP)(nil),
		(*Resource_RoutingInstance)(nil),
		(*Resource_Namespace)(nil),
	}
}

func init() {
	proto.RegisterEnum("github.com.michaelhenkel.config_controller.pkg.apis.v1.Response_Action", Response_Action_name, Response_Action_value)
	proto.RegisterType((*SubscriptionRequest)(nil), "github.com.michaelhenkel.config_controller.pkg.apis.v1.SubscriptionRequest")
	proto.RegisterType((*Response)(nil), "github.com.michaelhenkel.config_controller.pkg.apis.v1.Response")
	proto.RegisterType((*Resource)(nil), "github.com.michaelhenkel.config_controller.pkg.apis.v1.Resource")
}

func init() {
	proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f)
}

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xc7, 0x93, 0x6d, 0xbf, 0x6e, 0xf3, 0xf4, 0x1b, 0x95, 0xb9, 0x20, 0x9a, 0x84, 0x34, 0xf5,
	0x6a, 0xbb, 0xc0, 0xa1, 0x41, 0x42, 0xbb, 0x41, 0xda, 0x9f, 0x56, 0x64, 0x62, 0x8c, 0x62, 0x06,
	0x08, 0x6e, 0x26, 0xd7, 0x3d, 0x4b, 0x4c, 0x33, 0x3b, 0xd8, 0x4e, 0x27, 0x21, 0xf1, 0x18, 0x3c,
	0x02, 0x2f, 0xc1, 0x05, 0x6f, 0xc0, 0x3b, 0xa1, 0xb8, 0xc9, 0xfa, 0x07, 0xb8, 0x59, 0x7b, 0x17,
	0xdb, 0xc7, 0x9f, 0xef, 0xb1, 0x8f, 0xcf, 0x37, 0xa8, 0xc9, 0x95, 0xb4, 0x5a, 0x65, 0x19, 0x68,
	0x92, 0x6b, 0x65, 0x15, 0x7e, 0x9a, 0x08, 0x9b, 0x16, 0x7d, 0xc2, 0xd5, 0x35, 0xb9, 0x16, 0x3c,
	0x65, 0x90, 0xa5, 0x20, 0x87, 0x90, 0x11, 0xae, 0xe4, 0x95, 0x48, 0x2e, 0xa7, 0x77, 0x0c, 0x13,
	0xc2, 0x72, 0x61, 0xc8, 0xa8, 0xbd, 0xd3, 0x33, 0x66, 0xf0, 0x28, 0x11, 0x96, 0x7c, 0x2a, 0xa4,
	0xc8, 0x41, 0x13, 0x09, 0x36, 0x74, 0xb1, 0x4c, 0x64, 0x21, 0x97, 0xd1, 0x64, 0x90, 0x0f, 0x93,
	0xb0, 0xdc, 0x16, 0x72, 0xa5, 0x21, 0x1c, 0xb5, 0x59, 0x96, 0xa7, 0xac, 0x1d, 0x26, 0x20, 0x41,
	0x33, 0x0b, 0x83, 0x71, 0x26, 0x3b, 0xad, 0xe1, 0x81, 0x21, 0x42, 0x95, 0xa1, 0x75, 0xe4, 0x7c,
	0x4c, 0x6b, 0x1f, 0xdd, 0x7f, 0x53, 0xf4, 0x0d, 0xd7, 0x22, 0xb7, 0x42, 0x49, 0x0a, 0x9f, 0x0b,
	0x30, 0x16, 0x63, 0xb4, 0x26, 0xd9, 0x35, 0x04, 0xfe, 0xae, 0xbf, 0xb7, 0x49, 0xdd, 0x77, 0xeb,
	0xe7, 0x0a, 0xda, 0xa0, 0x60, 0x72, 0x25, 0x0d, 0x60, 0x8a, 0x56, 0x25, 0xdc, 0xb8, 0xf5, 0xad,
	0xe8, 0x90, 0xdc, 0xed, 0xcc, 0x84, 0x82, 0x51, 0x85, 0xe6, 0x40, 0x4b, 0x58, 0xc9, 0x54, 0xd9,
	0x20, 0x58, 0x59, 0x16, 0x53, 0x65, 0x03, 0x7c, 0x89, 0x1a, 0x8c, 0x97, 0x27, 0x0b, 0x56, 0x77,
	0xfd, 0xbd, 0xed, 0xe8, 0xf9, 0x02, 0x58, 0x77, 0x72, 0x72, 0xe4, 0x70, 0xb4, 0xc2, 0xb6, 0xf6,
	0x51, 0x63, 0x3c, 0x83, 0xd7, 0xd1, 0xea, 0x51, 0xa7, 0xd3, 0xf4, 0x30, 0x42, 0x8d, 0xb7, 0xbd,
	0xce, 0xd1, 0x45, 0xb7, 0xe9, 0x97, 0xdf, 0x9d, 0xee, 0x59, 0xf7, 0xa2, 0xdb, 0x5c, 0x69, 0xfd,
	0x6a, 0xb8, 0x0b, 0x74, 0xd9, 0xe1, 0x2f, 0x68, 0x7b, 0x24, 0xb4, 0x2d, 0x58, 0x76, 0x0e, 0xf6,
	0x46, 0xe9, 0x61, 0x75, 0x97, 0x3d, 0x62, 0xcc, 0xe0, 0x72, 0xee, 0x1d, 0x90, 0xba, 0xf4, 0x84,
	0xcb, 0x68, 0x32, 0xb8, 0xcd, 0xaf, 0xac, 0x2e, 0xa9, 0xdf, 0x01, 0x79, 0x37, 0xc3, 0x8d, 0x3d,
	0x3a, 0xa7, 0x84, 0xbf, 0xf9, 0xe8, 0x41, 0x35, 0xf5, 0x92, 0xf1, 0x54, 0x48, 0x38, 0x95, 0x16,
	0xf4, 0x15, 0xe3, 0x50, 0xdd, 0xfe, 0x87, 0xa5, 0x65, 0x31, 0x2f, 0x10, 0x7b, 0xf4, 0x5f, 0xda,
	0xf8, 0x06, 0xfd, 0x5f, 0x2d, 0x51, 0x55, 0x58, 0xd0, 0xae, 0x66, 0x5b, 0xd1, 0xab, 0xa5, 0x25,
	0x33, 0xc6, 0xc6, 0x1e, 0x9d, 0xd5, 0x99, 0x2a, 0x46, 0x95, 0x53, 0xb0, 0xb6, 0xe4, 0x62, 0x54,
	0xdc, 0xa9, 0x62, 0x54, 0x33, 0x58, 0x22, 0x24, 0xa4, 0xb1, 0x4c, 0x72, 0x38, 0xed, 0x05, 0xff,
	0x39, 0xdd, 0xb3, 0xc5, 0x75, 0x4f, 0x6f, 0x99, 0xb1, 0x47, 0xa7, 0x14, 0xf0, 0x57, 0x74, 0x4f,
	0xab, 0xc2, 0x0a, 0x99, 0xd4, 0x21, 0x41, 0xc3, 0x89, 0xbe, 0x5e, 0x5c, 0x94, 0xce, 0x82, 0x63,
	0x8f, 0xce, 0x6b, 0xe1, 0x67, 0x68, 0xb3, 0x74, 0x13, 0x93, 0x97, 0x8f, 0x6d, 0xdd, 0x09, 0x3f,
	0x24, 0x63, 0xa3, 0x2a, 0x89, 0x35, 0x90, 0x9c, 0xd7, 0x41, 0xb1, 0x47, 0x27, 0x3b, 0x8e, 0x11,
	0xda, 0xd0, 0x55, 0x0b, 0x45, 0x3f, 0x7c, 0xd4, 0x3c, 0x71, 0x4d, 0x7b, 0x72, 0xdb, 0xb3, 0xf8,
	0xbb, 0x8f, 0x70, 0xe5, 0x68, 0x7d, 0x38, 0x13, 0xc6, 0xbe, 0x67, 0x96, 0xa7, 0xf8, 0xc5, 0x5d,
	0xfb, 0xfe, 0x2f, 0xee, 0xb8, 0x73, 0xb8, 0xa8, 0x89, 0x3c, 0xf6, 0x8f, 0x0f, 0x3e, 0x4e, 0xfd,
	0x28, 0xc2, 0x19, 0x48, 0xf8, 0x07, 0x64, 0xe2, 0xf8, 0xa3, 0x76, 0xbf, 0xe1, 0x9c, 0xfb, 0xc9,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x64, 0x6b, 0xf0, 0x7b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConfigControllerClient is the client API for ConfigController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigControllerClient interface {
	SubscribeListWatch(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (ConfigController_SubscribeListWatchClient, error)
}

type configControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigControllerClient(cc grpc.ClientConnInterface) ConfigControllerClient {
	return &configControllerClient{cc}
}

func (c *configControllerClient) SubscribeListWatch(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (ConfigController_SubscribeListWatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConfigController_serviceDesc.Streams[0], "/github.com.michaelhenkel.config_controller.pkg.apis.v1.ConfigController/SubscribeListWatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &configControllerSubscribeListWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigController_SubscribeListWatchClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type configControllerSubscribeListWatchClient struct {
	grpc.ClientStream
}

func (x *configControllerSubscribeListWatchClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConfigControllerServer is the server API for ConfigController service.
type ConfigControllerServer interface {
	SubscribeListWatch(*SubscriptionRequest, ConfigController_SubscribeListWatchServer) error
}

// UnimplementedConfigControllerServer can be embedded to have forward compatible implementations.
type UnimplementedConfigControllerServer struct {
}

func (*UnimplementedConfigControllerServer) SubscribeListWatch(req *SubscriptionRequest, srv ConfigController_SubscribeListWatchServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeListWatch not implemented")
}

func RegisterConfigControllerServer(s *grpc.Server, srv ConfigControllerServer) {
	s.RegisterService(&_ConfigController_serviceDesc, srv)
}

func _ConfigController_SubscribeListWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigControllerServer).SubscribeListWatch(m, &configControllerSubscribeListWatchServer{stream})
}

type ConfigController_SubscribeListWatchServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type configControllerSubscribeListWatchServer struct {
	grpc.ServerStream
}

func (x *configControllerSubscribeListWatchServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _ConfigController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.michaelhenkel.config_controller.pkg.apis.v1.ConfigController",
	HandlerType: (*ConfigControllerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeListWatch",
			Handler:       _ConfigController_SubscribeListWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controller.proto",
}
